[build]
  base = "client"

[[redirects]]
  from = "https://github.com/blackcubes"
  to = "https://github.com/blackcubes"
  status = 200
  force = true

[[redirects]]
  from = "https://www.linkedin.com/in/eliasgutierrez1991/"
  to = "https://www.linkedin.com/in/eliasgutierrez1991/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200